version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing project dependencies using npm
      - npm install -g @angular/cli
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - echo Building project
      - yarn run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/teslaconnect'
  discard-paths: no
