version: "3"

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificate.crt:/etc/nginx/certificate.crt
      #- ./nginx/logs:/var/log/nginx
    ports:
      - "8080:8080"
