version: "3"

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./nginx/snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./nginx/ssl/certs/teslamotors.crt:/etc/ssl/certs/teslamotors.crt
      - ./nginx/ssl/certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt
      - ./nginx/ssl/private/selfsigned.key:/etc/ssl/private/selfsigned.key
    ports:
      - "443:443"
